### ISSUE TITLE
NuGet packages are missing

### ISSUE THREAD

**Issue by elbruno** [Microsoft/Quantum#1]
Hi

There seems to be an issue with the NuGet packages, none of them are available in NuGet. The search [Microsoft.Quantum] returns zero results >> https://www.nuget.org/packages?q=Microsoft.Quantum

Regards
-Bruno

**Comment by anpaz-msft** [comment]
Looks like you beat me to this. The packages albeit available, were indeed not searchable while we were ironing out some kinks. They are now mark as searchable so they should start appearing on search results soon.
Thanks!
