### ISSUE TITLE
File Microsoft.Quantum.Canon.nuspec is missing

### ISSUE THREAD

**Issue by ArtisanDuCode** [Microsoft/Quantum#10]
The file Microsoft.Quantum.Canon.nuspec is missing in the project Microsoft.Quantum.Canon.
there is the file Microsoft.Quantum.Canon.nuspec.v.template that is not included in the project Microsoft.Quantum.Canon.
![filemissing](https://user-images.githubusercontent.com/25029876/33911828-e1763444-df93-11e7-879d-8798b0f384ac.PNG)

**Comment by Arcani** [comment]
I am having issues running the TeleportationSample project, and see the same file missing on my solution explorer.  I also did not see the file in the repo either (https://github.com/Microsoft/Quantum/tree/master/Microsoft.Quantum.Canon)
