### ISSUE TITLE
Q# Arthimatic syntax error

### ISSUE THREAD

**Issue by rjinka** [Microsoft/Quantum#104]
Below code throws an error for arthematic syntax finaloutput += 1 and no error if i rewrite this to finaloutput = finaloutput + 1. Is this a bug or is it on purpose?

mutable finaloutput = 0; 
using(Qubits = Qubit[1]) 
{ 
Set(Initial,Qubits[0]);	
X(Qubits[0]); 
let res = M(Qubits[0]); 
if(res == One) 
{ 
set finaloutput += 1; 
} 

Set(Zero,Qubits[0]);

}

**Comment by ZORLAXX** [comment]
I can take a look at this.

**Comment by anpaz-msft** [comment]
Yeap, the `+=` is not a valid operator in Q#. Sorry.
The current Q# language reference can be found at:
https://docs.microsoft.com/en-us/quantum/language/

**Comment by anpaz-msft** [comment]
I see this suggestion posted in [UserVoice](https://quantum.uservoice.com/forums/906208-q-language), which is the right place for it. Closing this Issue as it's not specific to this Samples repository.
