### ISSUE TITLE
Build errors on Windows 10, VS Community 2017 - Sample does not compile

### ISSUE THREAD

**Issue by benprieur** [Microsoft/Quantum#113]
Hi, 

When compiling the sample I get these errors. Quantum assemblies are still not recognized as assemblies. These dependances are with yellow triangles in solution explorer.

_C:/Users/benoit/.nuget/packages/microsoft.quantum.canon/0.3.1811.203-preview/lib/netstandard2.0/Microsoft.Quantum.Canon.dll : error QS7010: The given file is not an valid assembly. [C:\Users\benoit\Quantum\Samples\src\Teleportation\TeleportationSample.csproj]
C:/Users/benoit/.nuget/packages/microsoft.quantum.development.kit/0.3.1811.203-preview/lib/netstandard2.0/Microsoft.Quantum.Primitives.dll : error QS7010: The given file is not an valid assembly. [C:\Users\benoit\Quantum\Samples\src\Teleportation\TeleportationSample.csproj]
C:/Users/benoit/.nuget/packages/microsoft.quantum.development.kit/0.3.1811.203-preview/lib/netstandard2.0/Microsoft.Quantum.Simulation.Common.dll : error QS7010: The given file is not an valid assembly. [C:\Users\benoit\Quantum\Samples\src\Teleportation\TeleportationSample.csproj]
C:/Users/benoit/.nuget/packages/microsoft.quantum.development.kit/0.3.1811.203-preview/lib/netstandard2.0/Microsoft.Quantum.Simulation.Core.dll : error QS7010: The given file is not an valid assembly. [C:\Users\benoit\Quantum\Samples\src\Teleportation\TeleportationSample.csproj]
C:/Users/benoit/.nuget/packages/microsoft.quantum.development.kit/0.3.1811.203-preview/lib/netstandard2.0/Microsoft.Quantum.Simulation.QCTraceSimulatorRuntime.dll : error QS7010: The given file is not an valid assembly. [C:\Users\benoit\Quantum\Samples\src\Teleportation\TeleportationSample.csproj]
C:/Users/benoit/.nuget/packages/microsoft.quantum.development.kit/0.3.1811.203-preview/lib/netstandard2.0/Microsoft.Quantum.Simulation.Simulators.dll : error QS7010: The given file is not an valid assembly. [C:\Users\benoit\Quantum\Samples\src\Teleportation\TeleportationSample.csproj]
C:\Users\benoit\.nuget\packages\microsoft.quantum.development.kit\0.3.1811.203-preview\build\Microsoft.Quantum.Development.Kit.targets(20,5): error MSB3073: La commande "dotnet "C:\Users\benoit\.nuget\packages\microsoft.quantum.development.kit\0.3.1811.203-preview\build\../tools/qsc/qsc.dll" build --format MsBuild  --input "TeleportationSample.qs" --references "C:\Users\benoit\.nuget\packages\microsoft.quantum.canon\0.3.1811.203-preview\lib\netstandard2.0\Microsoft.Quantum.Canon.dll" "C:\Users\benoit\.nuget\packages\microsoft.quantum.development.kit\0.3.1811.203-preview\lib\netstandard2.0\Microsoft.Quantum.Primitives.dll" "C:\Users\benoit\.nuget\packages\microsoft.quantum.development.kit\0.3.1811.203-preview\lib\netstandard2.0\Microsoft.Quantum.QsCompilerCommon.dll" "C:\Users\benoit\.nuget\packages\microsoft.quantum.development.kit\0.3.1811.203-preview\lib\netstandard2.0\Microsoft.Quantum.Simulation.Common.dll" "C:\Users\benoit\.nuget\packages\microsoft.quantum.development.kit\0.3.1811.203-preview\lib\netstandard2.0\Microsoft.Quantum.Simulation.Core.dll" "C:\Users\benoit\.nuget\packages\microsoft.quantum.development.kit\0.3.1811.203-preview\lib\netstandard2.0\Microsoft.Quantum.Simulation.QCTraceSimulatorRuntime.dll" "C:\Users\benoit\.nuget\packages\microsoft.quantum.development.kit\0.3.1811.203-preview\lib\netstandard2.0\Microsoft.Quantum.Simulation.Simulators.dll" --output obj\qsharp\src\" s'est arrêtée avec le code -2. [C:\Users\benoit\Quantum\Samples\src\Teleportation\TeleportationSample.csproj]_

Thank you.

**Comment by cristicmf** [comment]
I have the same question

**Comment by blfuentes** [comment]
I was having the same issue. Just closed the solution and opened it again. The references were recognized and everything worked.

**Comment by anpaz-msft** [comment]
As mentioned closing/opening the solution typically fixes these problems in Visual Studio.
One thing that I find interesting is the path reported is:
_C:\Users\benoit.nuget\packages\microsoft.quantum.development.kit\0.3.1811.203-preview\lib\netstandard2.0\Microsoft.Quantum.Simulation.Simulators.dll"_

but it should have a '\' between `betnoit` and `.nuget`. as in:
_C:\Users\benoit\.nuget\packages\microsoft.quantum.development.kit\0.3.1811.203-preview\lib\netstandard2.0\Microsoft.Quantum.Simulation.Simulators.dll"_

No idea of why that is the case. Maybe a bug in Visual Studio? Which version of VS 2017 are you using? The extension requires at least 15.8

**Comment by anpaz-msft** [comment]
Closing as this is not really an Issue with the samples.
https://stackoverflow.com is probably a better venue to ask these questions, the Q# team actively monitors [questions tagged with q#](https://stackoverflow.com/questions/tagged/q%23).
