### ISSUE TITLE
Missing Path to SDK Resolver DLL

### ISSUE THREAD

**Issue by NishkaDG** [Microsoft/Quantum#114]
## Could not load SDK Resolver. A manifest file exists, but the path to the SDK Resolver DLL file could not be found. ##

I followed the instructions at https://docs.microsoft.com/en-gb/quantum/install-guide/vs-2017?view=qsharp-preview but when I click on Samples\QSharpSamples.sln, I get the above error. As the file paths after the quoted error message mention NuGetSdkResolver.dll, in accordance to the tip on the installation webpage, I tried to attempt a NuGet Package Restore based on the instructions at https://docs.microsoft.com/en-gb/nuget/consume-packages/package-restore. However, I cannot find NuGet Package Manager in Tools > Options. 

Thank you for your time.

**Comment by NishkaDG** [comment]
I individually downloaded every file and package with the "NuGet" or "DLL" in the title; then I was getting errors such as "load failed" and, eventually, an error claiming that "Microsoft.NET.Sdk" was missing. By this point I felt it would be cleaner to clone the Q# repository again, but the "missing Microsoft.NET.Sdk" error did not go anywhere. I have no idea what I am doing wrong.
Thank you for your time.

**Comment by NishkaDG** [comment]
I individually downloaded every file and package with the "NuGet" or "DLL" in the title; then I was getting errors such as "load failed" and, eventually, an error claiming that "Microsoft.NET.Sdk" was missing. By this point I felt it would be cleaner to clone the Q# repository again, but the "missing Microsoft.NET.Sdk" error did not go anywhere. I have no idea what I am doing wrong.
Thank you for your time.

**Comment by anpaz-msft** [comment]
Did you figured this out? Looks like your installation of dotnet was missing or broken. What version of VS did you have?
If still a problem, I would suggest installing .net core from this URL: 
https://www.microsoft.com/net/download
and then, from the command line on a clean clone of this Samples repository run:
`dotnet build Samples/QsharpSamples.sln`
that is all you need.

**Comment by anpaz-msft** [comment]
Closing as this is not really an Issue with the samples.
https://stackoverflow.com is probably a better venue to ask these questions, the Q# team actively monitors [questions tagged with q#](https://stackoverflow.com/questions/tagged/q%23)

**Comment by Assisting** [comment]
Just as an FYI I've run into the same problem. You'll probably want to check for the existence of `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\Microsoft.Build.NuGetSdkResolver.dll`, in my case the whole NuGet folder was missing.

**Comment by mikejr76** [comment]
Assisting you mentioned "in my case the whole NuGet folder was missing." but you didn't mention how you got it?

**Comment by hussainb** [comment]
> Just as an FYI I've run into the same problem. You'll probably want to check for the existence of `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\Microsoft.Build.NuGetSdkResolver.dll`, in my case the whole NuGet folder was missing.

you should really mention how you were able to get that missing nuget folder, it will really "Assist" us.

**Comment by jgilpin** [comment]
I had the same error when only VS2017 build tools is installed. 
To remedy, I needed to install the Microsoft.VisualStudio.Component.NuGet.BuildTools component.

Used a command like this from powershell:
`Start-Process "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList 'modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools" --passive --add Microsoft.VisualStudio.Component.NuGet.BuildTools' -Wait -PassThru`

**Comment by Assisting** [comment]
Apologies to those who asked, my eventual solution was to copy/paste it from elsewhere in the file system. If you don't have it at all I'm sure @jgilpin 's suggestion would work.

**Comment by samneefs** [comment]
SDK resolver didn't exist (C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\Microsoft.Build.NuGetSdkResolver.dll)
@jgilpin 's command added the needed file.

**Comment by kylekampy** [comment]
I was able to get around this issue by simply running the "Repair" option from the Visual Studio Installer. It dropped in the missing .dll for me.

**Comment by YahiaEltantawy** [comment]
just install **Visual Studio SDK** in **Individual Tap with Visual Studio Installer**
