### ISSUE TITLE
Build status dead link

### ISSUE THREAD

**Issue by ChennyBaBy** [Microsoft/Quantum#12]
Build status in readme is a dead link

**Comment by anpaz-msft** [comment]
Thanks for reporting this. We changed to a new build definition without updating the README.md
It's now fixed.

**Comment by ChennyBaBy** [comment]
I have a question outside of this Issue, its about the "VSTS: Libraries github" in part of the Pull Request  pending checks. It's seems to be stuck on waiting for a while for all things that's been Queued up. I was wondering if it's broken or just takes a long time for it to come back.
