### ISSUE TITLE
CreateHubbardHamiltonian README.md is out of date

### ISSUE THREAD

**Issue by kmckiern** [microsoft/Quantum#127]
`HubbardSimulation.qs` and `HubbardSimulationSample.csproj` no longer exist (referenced in the manifest).

**Comment by anpaz-msft** [comment]
Thanks for bringing this up. This is about the README.md in 
https://github.com/Microsoft/Quantum/tree/master/Chemistry/CreateHubbardHamiltonian
as the name implies this sample shows how to create Hubbard Hamiltonians in C# using the chemistry library.  The README.md was probably copied from the original https://github.com/Microsoft/Quantum/tree/master/Samples/src/HubbardSimulation which does the HubbardSimulation without using the chemistry library (it predates it).
It indeed needs to be fixed.
