### ISSUE TITLE
No definition found for QuantumSimulator in vscode under mac

### ISSUE THREAD

**Issue by bigfg** [Microsoft/Quantum#136]
## THANKS FOR TAKING THE TIME TO REPORT AN ISSUE ##

Please be advised that we are collecting feedback for the entire 
Microsoft Quantum Development Kit at [user voice](https://quantum.uservoice.com/). 

It would be much better for us if you  leave your suggestions,
requests and bugs (or praises!) there.

Thanks!

**Comment by cgranade** [comment]
Thanks for letting us know about the problem. Would you be able to provide a bit more detail as to what went wrong, so that we can better address the issue? Thanks!

**Comment by anpaz-msft** [comment]
The QuantumSimulator is a C# component, does it requires the Omnisharp C# extension to be recognized by Intellisense.
Not sure what the exact bug is here. As Chris pointed out, we need more info.

At any case, closing as this is not really an Issue with the samples.
https://stackoverflow.com is probably a better venue to ask these questions, the Q# team actively monitors [questions tagged with q#](https://stackoverflow.com/questions/tagged/q%23)
