### ISSUE TITLE
Include QDK at Visual Studio install

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/Quantum#142]
It would be cool for people setting up new development environments to be able to select at install time to download and install the QDK. See the screen cap below for an example:

![image](https://user-images.githubusercontent.com/6486256/52893000-e9b8f900-314c-11e9-8e1b-e55396b27cac.png)

Thanks!

**Comment by cgranade** [comment]
Great idea, thanks! We've marked it on our list of things we want to look into.

**Comment by muslumzaric** [comment]
tebrikler

**Comment by guenp** [comment]
We're looking into this - tagging @ricardo-espinoza
