### ISSUE TITLE
MacOS issues

### ISSUE THREAD

**Issue by micromax** [Microsoft/Quantum#15]
i can't install QsharpVSIX.vsix file in my Env or it will work only for windows OS

**Comment by anpaz-msft** [comment]
Currently, only Visual Studio (Community / Pro / Enterprise) are supported. Mac and Visual Studio Code support are on our interest list, though, and under investigation for future support.

We are tracking this at uservoice:
https://quantum.uservoice.com/forums/906943-setup-and-visual-studio-integration/suggestions/32588963-visual-studio-for-mac-support

Feel free to leave your comments or votes there.

**Comment by alan-geller** [comment]
We have released a version of the development kit that works on Mac. See https://docs.microsoft.com/quantum/quantum-installconfig for installation instructions and links.
