### ISSUE TITLE
Can I use Quantum Development Kit with Visual Studio Code

### ISSUE THREAD

**Issue by rafidka** [Microsoft/Quantum#16]
Is there anyway to use QDK with VSC?

**Comment by anpaz-msft** [comment]
Currently, only Visual Studio (Community / Pro / Enterprise) are supported. Mac and Visual Studio Code support are on our interest list, though, and under investigation for future support.

We are tracking this at uservoice:
https://quantum.uservoice.com/forums/906943-setup-and-visual-studio-integration/suggestions/32588963-visual-studio-for-mac-support

Feel free to leave your comments or votes there.

**Comment by rafidka** [comment]
Thanks, @anpaz-msft . I posted a comment regarding Visual Studio Code. Should I close this? Or perhaps leave it for sometime for others to see it and up-vote the link you sent?

**Comment by alan-geller** [comment]
We have released a version of the development kit that works with Visual Studio Code. See https://docs.microsoft.com/quantum/quantum-installconfig for links and installation instructions.
