### ISSUE TITLE
RandomIntPow2 doesn't work when using ToffoliSim

### ISSUE THREAD

**Issue by Strilanc** [Microsoft/Quantum#165]
Attempting to generate random numbers via `RandomIntPow2` in a test using a Toffoli simulator results in the following exception:

> Cannot create an instance of Microsoft.Quantum.Primitive.Random because it has no body definition and it is not implemented by this Simulator.

**Comment by alan-geller** [comment]
Oops... I thought Random was defined in a base class, but it's not. Working on a fix right now.

**Comment by alan-geller** [comment]
This should be fixed in the latest NuGet packages. Thanks for the bug report!!
