### ISSUE TITLE
BellTest does not exist

### ISSUE THREAD

**Issue by EnginSahinCE** [Microsoft/Quantum#17]
When I try to run the example in "Creating a Bell State in Q #" I get the following errors and it is not compiled. (Framework 4.6.1, Platform target: x64)

`1>------ Build started: Project: Bell, Configuration: Debug x64 ------
1>C:\Users\engin\source\repos\Bell\Bell\Driver.cs(16,31,16,39): error CS0103: The name 'BellTest' does not exist in the current context
1>C:\Users\engin\source\repos\Bell\Bell\Driver.cs(17,26,17,34): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'numZeros'.
1>C:\Users\engin\source\repos\Bell\Bell\Driver.cs(17,36,17,43): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'numOnes'.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

Bell.qs
`
namespace Quantum.Bell
{
    open Microsoft.Quantum.Primitive;
    open Microsoft.Quantum.Canon;

    operation Set (desired: Result, q1: Qubit) : ()
    {
        body
        {
            let current = M(q1);
            if (desired != current)
            {
                X(q1);
            }
        }
    }

	operation BellTest (count : Int, initial: Result) : (Int,Int)
    {
        body
        {
            mutable numOnes = 0;
            using (qubits = Qubit[1])
            {
                for (test in 1..count)
                {
                    Set (initial, qubits[0]);

                    let res = M (qubits[0]);

                    // Count the number of ones we saw:
                    if (res == One)
                    {
                        set numOnes = numOnes + 1;
                    }
                }
                Set(Zero, qubits[0]);
            }
            // Return number of times we saw a |0> and number of times we saw a |1>
            return (count-numOnes, numOnes);
        }
    }
}
`

driver.cs
`
using Microsoft.Quantum.Simulation.Core;
using Microsoft.Quantum.Simulation.Simulators;

namespace Quantum.Bell
{
    class Driver
    {
        static void Main(string[] args)
        {
            using (var sim = new QuantumSimulator())
            {
                // Try initial values
                Result[] initials = new Result[] { Result.Zero, Result.One };
                foreach (Result initial in initials)
                {
                    var res = BellTest.Run(sim, 1000, initial).Result;
                    var (numZeros, numOnes) = res;
                    System.Console.WriteLine(
                        $"Init:{initial,-4} 0s={numZeros,-4} 1s={numOnes,-4}");
                }
            }
            System.Console.WriteLine("Press any key to continue...");
            System.Console.ReadKey();
        }
    }
}
`

**Comment by anpaz-msft** [comment]
Seems like a problem with the c# compiler having problem with ValueTuples.

Are you using VS2017? Was the ValueTuple package correctly installed? Do you know which version of the C# compiler you are using?

**Comment by EnginSahinCE** [comment]
I use VS2017 ent. I installed Microsoft.quantum.canon, ms.quantum.dev.kit and System.ValueTuple (v4.4.0). i don't know version of the c# compiler, how can i learn this?

**Comment by EnginSahinCE** [comment]
the problem is "C# code contains ',' instead of '.' as decimal separator" issue#6. I changed english(american)  and the problem is solved, it is compiling now.

**Comment by He-ya** [comment]
I also have the same question in the line 18 and 19 in this code:
The name 'BellTest' does not exist in the current context
Cannot infer the type of implicitly-typed deconstruction variable 'numZeros'. [Bell]
Cannot infer the type of implicitly-typed deconstruction variable 'numOnes'. [Bell]
Cannot infer the type of implicitly-typed deconstruction variable 'agree'. [Bell]
I can't fix the bug by the command:
dotnet add package System.ValueTuple
See my code: https://gist.github.com/He-ya/4cc50073e75d5dfb2aeeb535b5dec87f

**Comment by cgranade** [comment]
@He-ya: Thanks for providing the C# host program! From the details provided, it looks like the C# compiler isn't finding the `BellTest` class that the Q# compiler generates from the `BellTest` operation. Would you be able to provide the Q# code you used as well? Thanks!

**Comment by He-ya** [comment]
@cgranade: Thanks. The tutorial Q# code Bell.qs from the said website:
https://gist.github.com/He-ya/4e5233749d63667a9703eba088d9b677

**Comment by He-ya** [comment]
I can't even run the command 'dotnet run' with the TeleportationSample.qs file, the sample file in the tutorial.
https://gist.github.com/He-ya/26a480579dc24904cc9614e434198909

**Comment by He-ya** [comment]
I don't know if the error occurs while compiling it under the Mac OSX.
