### ISSUE TITLE
difference between VS template and docs

### ISSUE THREAD

**Issue by crazy4pi314** [Microsoft/Quantum#18]
I was just walking through the tutorial from this [doc page](https://docs.microsoft.com/en-ca/quantum/quantum-writeaquantumprogram?view=qsharp-preview) and I find that the VS solution file `Operation.qs` (that we rename to Bell.qs) has one extra line.
- Snippet from the docs
```
namespace Quantum.Bell
{
    open Microsoft.Quantum.Primitive;

    operation Operation () : ()
    {
        body
        {

        }
    }
}
```

- What VS generated in `Operation.qs`
```
namespace Quantum.Bell
{
    open Microsoft.Quantum.Primitive;
    open Microsoft.Quantum.Canon;

    operation Operation () : ()
    {
        body
        {

        }
    }
}
```

It still works just fine, just noting the mismatch in the docs and the VS template.

Thanks for such an awesome project!!

**Comment by tcNickolas** [comment]
We have updated the docs to match VS template. Thank you for pointing this out!
