### ISSUE TITLE
OpenQASMReader Sample fails to read and convert U2(0.0,3.14159265358979, q[1]); to Q#

### ISSUE THREAD

**Issue by frajos100** [microsoft/Quantum#183]
## THANKS FOR TAKING THE TIME TO REPORT AN ISSUE ##

Please be advised that we are collecting feedback for the entire 
Microsoft Quantum Development Kit at [user voice](https://quantum.uservoice.com/). 

It would be much better for us if you  leave your suggestions,
requests and bugs (or praises!) there.

OpenQASMReader Sample fails to read and convert U2(0.0,3.14159265358979, q[1]); to Q#

**Comment by bromeg** [comment]
The relevant sample has been moved to : https://github.com/qsharp-community/qsharp-integrations
