### ISSUE TITLE
Using Shor's algorithm to solve discrete logarithm problem

### ISSUE THREAD

**Issue by imvieira** [microsoft/Quantum#185]
I have read about Shor's algorithm and my understanding is that it can be used to factor large numbers efficiently. Can Shor's algorithm, though, be used to solve this problem:

Find the number 𝑒 e  given the following information (Assume that 𝑃 P , 𝐶 C , 𝑁 N  and 𝑒 e  are all large, say 2048-bit integers):  the integers 𝑃 P  and 𝑁 N the integer 𝐶 C  where 𝐶=𝑃𝑒mod𝑁 C = P e mod N If so, how does this algorithm work? 

Please explain it simply how can I solve this problem or a similar one using it, as I am not familiar with quantum mechanics.

**Comment by imvieira** [comment]
I have started using Qiskit since August 2018 with jupyter notebook. 
Last week I went through quantum experience website and how amazing is the dashboard and how easy is to play with quantum information.
I am studying one more time some fundamentals and then, I have plans to apply my question using Qiskit.

**Comment by cgranade** [comment]
Thanks for your report, @imvieira. I think you have the wrong repository, however, in that this is the repository for Quantum Development Kit samples.
