### ISSUE TITLE
Reference to unknown namespace Microsoft.Quantum.Primitive

### ISSUE THREAD

**Issue by leeli73** [Microsoft/Quantum#19]
I set up a QSharpTestProject,but I can't run it.
There are my problems.

error 	Reference to unknown namespace Microsoft.Quantum.Primitive	QSharpTestProject1

error		The namespace body is invalid	

And I set Windows to use US number,but it can't run.

**Comment by KaptenDavidsson** [comment]
Got the same error. Make sure you use .NET Framework 4.6.1, it solved it for me.
