### ISSUE TITLE
Questions about the future

### ISSUE THREAD

**Issue by manuelelucchi** [Microsoft/Quantum#2]
The Quantum Dev Kit is great and the tutorial are well done, but i have a few question about the future:
1) Will it be available on Linux or Mac OS in the future?
2) Will it be usable even without Visual Studio (ex: with a normal text editor)?
3) Would the Q# assembly be invoked also from other languages like C++?

I hope the Microsoft Quantum Project will group up even more!
Regards 
Manuele

**Comment by anpaz-msft** [comment]
Currently, only Visual Studio (Community / Pro / Enterprise) are supported. Mac and Visual Studio Code support are on our interest list, though, and under investigation for future support.

We are tracking this at uservoice:
https://quantum.uservoice.com/forums/906943-setup-and-visual-studio-integration/suggestions/32588963-visual-studio-for-mac-support

Feel free to leave your comments or votes there.
