### ISSUE TITLE
Where is the QDK

### ISSUE THREAD

**Issue by kant2002** [microsoft/Quantum#209]
I go to this website from https://cloudblogs.microsoft.com/quantum/2019/07/11/microsoft-quantum-oss-available-github/ where it is announced that QDK is open-sourced, but could not find anything on the MS github.

It is not clear, what's open-sourced then, since this repository was already present for relatively long time.

**Comment by cgranade** [comment]
Thanks for your question! The Quantum Development Kit consists of a few different components, as [summarized in the documentation](https://docs.microsoft.com/quantum/#microsoft-quantum-development-kit-components). We're very excited that to make the [Q# compiler](https://github.com/microsoft/qsharp-compiler), [Q# runtime](https://github.com/microsoft/qsharp-runtime), and the [IQ# kernel](https://github.com/microsoft/iqsharp) available open source, adding to the [Q# libraries](https://github.com/microsoft/QuantumLibraries/), the [quantum katas](https://github.com/microsoft/quantumkatas), and to the samples in this repository. If you're interested in contributing to the Quantum Development Kit, the [contribution guide](https://docs.microsoft.com/quantum/contributing/index#where-do-contributions-go) lists the different repositories that we use to work on the Quantum Development Kit.

Thanks again for your question, and for being a part of the quantum development community!

**Comment by kant2002** [comment]
I did not look at the docs. Generally I caught in the loop between blog post which point to https://www.microsoft.com/en-us/quantum/development-kit and "Contribute to our open source QDK" which point to the blog post again. Your links really helpful. 

Thanks!!!
