### ISSUE TITLE
K-Means

### ISSUE THREAD

**Issue by endeffects** [microsoft/Quantum#229]
Is there any sample for a k-means algorithm available?

**Comment by emzatos** [comment]
@endeffects I would like to ask for clarification on what you are looking for in a k-means implementation. Searching on Google, I found one implementation described [here](https://towardsdatascience.com/quantum-machine-learning-distance-estimation-for-k-means-clustering-26bccfbfcc76) that simply replaces the distance function with quantum technology, essentially providing something very simple to implement but overwhelmingly trivial in design. [This](https://arxiv.org/pdf/1812.03584.pdf) is much more elaborate and even suggests a speedup over the traditional algorithm. It is, however, very involved and may go beyond the scope of a sample implementation.

**Comment by endeffects** [comment]
Thanks for your response, well i was looking for a sample to cluster data.

**Comment by guenp** [comment]
Closing this issue since it looks like we don't have such a sample and are not planning to add one at this time. We are open for contributions though so feel free to re-open if anyone would like to help implement this.
