### ISSUE TITLE
Teleportation sample generates an exception

### ISSUE THREAD

**Issue by bethz** [microsoft/Quantum#259]
**Describe the bug**
The C# Teleportation sample has an exception.
It was referenced [here](https://github.com/microsoft/Quantum/blob/master/README.md).

**To Reproduce**
1. docker run -it --name iqsharp-container -p 8888:8888 iqsharp /bin/bash
 
2. cd ~/samples/getting-started/teleportation && python host.py
3. it ran but noted 
Released qubits are not in zero state.

4. then tried c#:
cd ~samples/getting-started/teleportation && dotnet run

3. see exception
![image](https://user-images.githubusercontent.com/6098674/67647469-d3348580-f908-11e9-862c-fd47745c5a70.png)

**Expected behavior**
Did not expect an exception

**Screenshots**
see above.

**System information**
 - Docker container mentioned above on Windows 10

**Additional context**
I filed a PR to fix the folder hierarchy for location of teleportation sample.

**Comment by cgranade** [comment]
Thanks for the report, @bethz! Looks like this was a case of accidentally writing `M` instead of `MResetZ`; it should be fixed incidentally with #256, in any case.

**Comment by cgranade** [comment]
I've confirmed that this has now been resolved in local testing, but please feel free to reopen the issue if you run into it again. Thanks for your report! ♥
