### ISSUE TITLE
entanglement?

### ISSUE THREAD

**Issue by buhtig314** [Microsoft/Quantum#26]
in the teleportation sample, cnot(msg,here) followed by h(msg). my question is why a h gate could be applied to single bit msg, since msg & here are in entanglement state, i.e. they are unseperatable . am i missed anything?

**Comment by tcNickolas** [comment]
Entanglement means that the qubits' states cannot be described separately. The qubits themselves are still separate entities and can have single-qubit gates applied to them individually (or the can have multi-qubit gates applied to one of the entangled qubits and some other qubits). Gates applied to one of the entangled qubits will impact the joint state of both qubits.

**Comment by buhtig314** [comment]
Thanks, i have got the answer after some further study.
