### ISSUE TITLE
LaTeX rendering is broken

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/Quantum#271]
It seems like most all of the LaTeX math rendering for these pages is broken, see on this page \ket in the first line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 139b4939-525f-d0b4-40e4-c912f5fcff48
* Version Independent ID: b00ec85c-4a1f-9706-3ea6-921e4f463d6c
* Content: [R1 operation (Microsoft.Quantum.Intrinsic) - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic.r1?view=qsharp-preview#feedback)
* Content Source: [api/qsharp/microsoft.quantum.intrinsic.r1.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/api/qsharp/microsoft.quantum.intrinsic.r1.yml)
* Product: **quantum**
* GitHub Login: @anpaz-msft

**Comment by numpde** [comment]
bra-ket notation renders on [this page](https://docs.microsoft.com/en-us/quantum/concepts/dirac-notation?view=qsharp-preview) but not on the page [cited](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic.r1?view=qsharp-preview#feedback) in this issue. 
Looking at the source, there is MathJax.Hub.Config that includes definitions of TeX macros for ket/bra/braket/etc. Maybe the mathjax [braket extension](http://docs.mathjax.org/en/latest/input/tex/extensions/braket.html) should be loaded instead?

**Comment by cgranade** [comment]
Closing, as I believe this has now been fixed. Please feel free to reopen if the issue has not been resolved. Thanks for reporting!
