### ISSUE TITLE
Consider supporting TensorFlow/CNTK

### ISSUE THREAD

**Issue by AceHack** [Microsoft/Quantum#30]
Please consider providing a runtime to TensofFlow/CNTK

See TensorFlow repo issue here
https://github.com/tensorflow/tensorflow/issues/16745

See CNTK repo issue here
https://github.com/Microsoft/CNTK/issues/2918

**Comment by alan-geller** [comment]
Sorry, this isn't in our road map.
How would you use TensorFlow and Q# together?

**Comment by AceHack** [comment]
Running tensor flow on a quantum computer/simulator
