### ISSUE TITLE
Sample Wine of QML library stuck in training

### ISSUE THREAD

**Issue by geduardo** [microsoft/Quantum#315]
**Describe the bug**
Sample Wines of Quantum Machine Learning gets stuck at "Beginning training at start point #0..."

**To Reproduce**
1. Run the sample Wine of the branch "feature/qml"

**Expected behavior**
Complete the training as it does in the sample Half moons, that works correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/48300381/74609705-e1dbbe00-50ec-11ea-8cdc-a79414794760.png)

**System information**
 - OS: Windows 10
 - Device: Surface Pro 2017 (i5-7300U) 

**Additional context**
I don't know how long it should take but it's been running for quite some time. It looks like it gets stuck in the training. The TaskManager shows high activity in the process (80%).

**Comment by cgranade** [comment]
It's in general significantly slower than half-moons just due to the much larger data set. On some systems, we've seen that setting the `OMP_NUM_THREADS` environment variable to `1` can help, as the OpenMP-based parallelization can sometimes be ineffective for small numbers of qubits.

**Comment by geduardo** [comment]
How long should it take? I set  OMP_NUM_THREADS=1 and it's been running for more than one hour and still is stuck in the same step as the image. For comparison, half-moons takes 1-2 min to complete.  We should make sure that the first example on the QML library is clear and runnable in "acceptable times in reasonable hardware", if not it can create confusion with the user not being sure if it is really working.

**Comment by cgranade** [comment]
Alex raised the point that the optimization landscape may be unfavorable for this particular example such that some unlucky parameter selections may take a little while. I’m still in the process of further diagnosing the performance issue for this sample, my apologies for the delay.

**Comment by cgranade** [comment]
This issue may be related: https://github.com/microsoft/qsharp-runtime/issues/150
It looks like that may also explain some of the odd profiling behavior seen when trying to analyze the problem.

**Comment by geduardo** [comment]
Ok, thanks! I'll keep an eye on this, but maybe it is more convenient to change to the half-moons example for now for the QML library introduction. What do you think?

**Comment by cgranade** [comment]
> Ok, thanks! I'll keep an eye on this, but maybe it is more convenient to change to the half-moons example for now for the QML library introduction. What do you think?

I think that makes sense even without the performance issue. Half-moons is a bit more explicit and easier to get into, I think?

**Comment by cgranade** [comment]
As an update, I think the performance issue should be resolved by #234. That will take updating the packages used by the sample, but once CI completes on that PR we should be able to update the two QML samples as well.

**Comment by geduardo** [comment]
With the new verbose update, it's clear that it doesn't get stuck. However, it still takes very long, but I guess is the expected behavior.

**Comment by cgranade** [comment]
Closing, as we've made significant performance improvements with #234 and as verbosity helps in communicating progress to users. Thanks!
