### ISSUE TITLE
Could not install iqsharp into your Jupyter configuration, Could not install iqsharp into your Jupyter configuration, as `jupyter` was not found on your PATH. 

### ISSUE THREAD

**Issue by cloudmelon** [microsoft/Quantum#360]
Use **dotnet iqsharp install**  get below error and already installed Python 2.6 and 3.7 as well as Anaconda

Doc URL
https://docs.microsoft.com/en-us/quantum/install-guide/pyinstall

**Describe the bug**
A clear and concise description of what the bug is, and which sample or samples you encountered the bug in.

[ERROR] Could not install iqsharp into your Jupyter configuration, as `jupyter` was not found on your PATH. Please make sure that Jupyter is installed and is on your PATH. If you are using conda or venv, please make sure that you have the correct environment activated.

Full exception details:
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.Jupyter.Core.KernelApplication.InstallKernelSpec(Boolean develop, LogLevel logLevel, String prefix, IEnumerable`1 extraInstallArgs, IDictionary`2 additionalFiles, IEnumerable`1 additionalKernelArguments, String pathToTool)

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/4621560/82550233-1a5cbf00-9b56-11ea-90ae-3176ec989d3d.png)

**System information**

**Additional context**

**Comment by cloudmelon** [comment]
To resolve this problem, need to reboot after installed Python 2.6 and 3.7 as well as Anaconda, also need to make sure if VSCode was pointed to the right Python version ( 3.7 in my case ). 
Best practice is :
Also create Python virtual env when install qsharp and test Q sharp program in the env ( if you've chosen Python to play with Q# like me )

**Comment by rmshaffer** [comment]
Thanks for trying Q#, and thanks for sharing your solution to this issue!
