### ISSUE TITLE
Browse samples page: titles rendering with "Q\#" instead of "Q#"

### ISSUE THREAD

**Issue by gillenhaalb** [microsoft/Quantum#363]
Looks like the escape character is getting included in the titles. This is both on the browse page and the individual pages.
E.g.:
https://docs.microsoft.com/en-us/samples/browse/?languages=qsharp
https://docs.microsoft.com/en-us/samples/microsoft/quantum/run-q-programs-from-python-or-net/

**Comment by cgranade** [comment]
Good catch, thank you! I've tried to fix that in some places, but I think this likely got introduced when moving from [atx_closed style](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md003) (leading and trailing `#` characters) to atx style (leading `#` characters only) for heading, as an atx_closed header ending with Q# looks like an atx header ending with Q. Unfortunately, atx_closed is not supported for onboarding to docs.microsoft.com/samples, prompting this issue.

**Comment by guenp** [comment]
Looks like this issue has been resolved in the meantime. Thanks @gillenhaalb for flagging and @cgranade for taking a look!
