### ISSUE TITLE
Conversion Questions

### ISSUE THREAD

**Issue by jainvasu631** [microsoft/Quantum#367]
How to find size i.e. number of bits of LittleEndian.
How to convert LittleEndian to Qubit[]?
How to access bits in LittleEndian?

**Comment by cgranade** [comment]
A value of type `LittleEndian` isn't itself an array, but wraps a value of type `Qubit[]`. Thus, to find the length of the underlying register wrapped as a `LittleEndian` value, you can use the [unwrap operator (`!`)](https://docs.microsoft.com/quantum/user-guide/language/expressions#unwrap-expressions) to get back an array that you can pass to `Length`. For instance, `Length(register!)` works for `register : LittleEndian`.

**Comment by cgranade** [comment]
Thanks for your question, and please feel free to file an issue here if you find a problem with the samples or have a feature request. We're also always happy to answer questions you may be both here, and on external sites such as https://quantumcomputing.stackexchange.com/ or https://gitter.im/qsharp-community/community. Thanks!
