### ISSUE TITLE
Incorrect phase mentioned in documentation

### ISSUE THREAD

**Issue by sabarinathh** [microsoft/Quantum#370]
S gate does a pi / 2 phase shift. Its written as pi / 4 in the documentation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e68e0e4d-b557-f947-a9c7-870f9fc3370e
* Version Independent ID: 31ec5ee4-913f-1467-dded-d10cf1e6c492
* Content: [S operation (Microsoft.Quantum.Intrinsic) - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic.s)
* Content Source: [api/qsharp/microsoft.quantum.intrinsic.s.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/api/qsharp/microsoft.quantum.intrinsic.s.yml)
* Product: **quantum**
* GitHub Login: @anpaz-msft

**Comment by cgranade** [comment]
Thanks for raising this; as discussed at microsoft/qsharp-runtime#258, the documentation is correct as written, as the `S` operation can be described by the matrix 𝑆 = (1 0 \\ 0 𝑖). Please feel free to re-open this issue if there's something that we missed. Thank you!
