### ISSUE TITLE
RippleCarryAdderCDKM not releasing qubits in zero state on completion

### ISSUE THREAD

**Issue by apm04** [microsoft/Quantum#375]
I have converted the Jupyter notebook AdderExample.ipynb from 
https://github.com/microsoft/Quantum/tree/master/samples/arithmetic
to a standalone program with a host.py and TestAdd.qs. (uploaded, remove '.txt')

[host.py.txt](https://github.com/microsoft/Quantum/files/4815384/host.py.txt)
[TestAdd.qs.txt](https://github.com/microsoft/Quantum/files/4815385/TestAdd.qs.txt)

The adder works as expected with RippleCarryAdderTTK and RippleCarryAdderD.

With RippleCarryAdderCDKM the following error message is given:

Unhandled exception. Microsoft.Quantum.Simulation.Simulators.Exceptions.ReleasedQubitsAreNotInZeroState: Released qubits are not in zero state.

It appears the implementation of RippleCarryAdderCDKM is not releasing all internally used qubits on completion. Curiously the error does not appear using the Jupyter notebook itself.

**System information**
 - OS: Ubuntu 18.04
 - Python 3.6.9
 - Visual Studio Code 1.46.1
 - MS Quantum Development Kit for Visual Studio Code 0.11.20060403

**Comment by cgranade** [comment]
Thanks for raising this, I believe that this should be addressed by https://github.com/microsoft/QuantumLibraries/pull/303, but please let us know if the issue persists for you. Thank you!
