### ISSUE TITLE
Port order-finding sample to Q#

### ISSUE THREAD

**Issue by msoeken** [microsoft/Quantum#376]
Currently, the order-finding sample uses a C# host. This can be changed to a Q# host.

**Comment by manav28** [comment]
Could I take this one?

**Comment by cgranade** [comment]
@manav28: If you're interested, we'd definitely love a contribution to this one! A good place to start could be looking at the [contribution guidelines for code](https://docs.microsoft.com/quantum/resources/contributing/code), but we're also happy to answer questions here as well. Thank you!

**Comment by manav28** [comment]
Are there any examples of a Q# host for reference? Are we porting the Q# host to a .qs file or a jupyter notebook?

**Comment by cgranade** [comment]
Most of the samples have been modified to use Q# standalone programs, as detailed in the [command-line part of the user guide](https://docs.microsoft.com/quantum/user-guide/host-programs?tabs=tabid-python#q-from-the-command-line). Happy to help if you have any questions, though, and we greatly appreciate the contribution!

**Comment by cgranade** [comment]
This should be closed thanks to #392. Thank you so much, @manav28!
