### ISSUE TITLE
Replacing with "opaque box"

### ISSUE THREAD

**Issue by marktab** [microsoft/Quantum#384]
Per https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/black-box
suggest replacing with "opaque box"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44bfbe3c-0cee-b6a7-95b2-ef0707eb17be
* Version Independent ID: fe3e9d66-52ba-c730-6a4d-b9fc6a19011a
* Content: [Microsoft.Quantum.Oracles - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.oracles)
* Content Source: [api/qsharp/Microsoft.Quantum.Oracles.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/api/qsharp/Microsoft.Quantum.Oracles.yml)
* Product: **quantum**
* GitHub Login: @anpaz-msft

**Comment by anpaz-msft** [comment]
@KittyYeungQ can we fix this?

**Comment by KittyYeungQ** [comment]
@anpaz-msft Consulted team implementing site-wide changes. This term is not listed to be changed.
