### ISSUE TITLE
Feature request: qpic simulator for QCTraceSimulator optimal depth circuits

### ISSUE THREAD

**Issue by fvirdia** [microsoft/Quantum#462]
Hi there,

We have been working on updating the Grover-blocks [1] source code [2] to adopt the changes made to the QCTraceSimulator since our release. In particular, the trace simulator can now output circuits minimising depth or width.

At the same time, I've been playing with the qpic-simulator [3]. We used it to generate a diagram [4] for the quantum circuit of the AES S-box. However, it seems to generate the picture for the circuit with optimal width. 

I'm writing to ask if it would be possibile to integrate the qpic-simulator's code with the QCTracerSimulator, such that one can ask for a circuit diagram with optimal depth. This would be neat and would also allow us to understand some of the more surprising savings in T-depth obtained by the compiler (cf. Section 4.7 of [1]).

Cheers
Fernando

**References**
[1] Samuel Jaques, Michael Naehrig, Martin Roetteler, and Fernando Virdia, "Implementing Grover oracles for quantum key search on AES and LowMC". Preprint available at https://eprint.iacr.org/2019/1146.
[2] [https://github.com/microsoft/grover-blocks](https://github.com/microsoft/grover-blocks)
[3] [https://github.com/microsoft/Quantum/tree/master/samples/runtime/qpic-simulator](https://github.com/microsoft/Quantum/tree/master/samples/runtime/qpic-simulator)
[4] [https://fundamental.domains/sbox.pdf](https://fundamental.domains/sbox.pdf)

**Comment by cgranade** [comment]
@msoeken, I think you were looking at something along these lines recently?

**Comment by msoeken** [comment]
This issue can be addressed by passing an explicit instance to `QubitManager` in

https://github.com/microsoft/Quantum/blob/76ee850d0f9b7dd39887d741ac7c2e17a6a1b75a/samples/runtime/qpic-simulator/simulator/Simulator.cs#L8

and set `encourageReuse` to `false`:

https://github.com/microsoft/qsharp-runtime/blob/1b726d6b41af86a50e544197dfa10858e8fea8f8/src/Simulation/Common/QubitManager.cs#L168

**Comment by cgranade** [comment]
@fvirdia: In light of @msoeken's comment above, I'm going to go on and close this issue, but please feel free to re-open if there's anything else we can add to help with your usecase! Thank you!
