### ISSUE TITLE
Extending Q# Grover's Algorithm for QML implementation of XGBoost

### ISSUE THREAD

**Issue by gokulsan** [microsoft/Quantum#463]
Is it possible to use the Q# implementation of Grover's Algorithm for XGBoost and similar kind of Gradient Boosting Algorithms. What would be the required Qubit configurations and Quantum Register Structure? This is inspired by the following question in the Quantum Computing Stack Exchange. 

https://quantumcomputing.stackexchange.com/questions/2057/gradient-boosting-akin-to-xgboost-using-a-quantum-device

**Comment by cgranade** [comment]
Much obliged for the suggestion! I think we're not currently looking into adding boosting to the quantum machine learning library at this time, so I'll go on and close the issue for now, but please feel free to re-open if there's any additional context. Thank you!
