### ISSUE TITLE
Connection error when listing targets in CLI

### ISSUE THREAD

**Issue by giobb** [microsoft/Quantum#466]
Hi everyone

I always get the issue below on my work machine. This machine is the standard issue that's connecting to corpnet via MS VPN from home. It doesn't happen on my personal machine though. If it's not Quantum-CLI related, I'm just wondering why it's only on this particular subcommand, (the **workspace set** obviously works)

![Quantum - another issue](https://user-images.githubusercontent.com/15137038/107689280-7aa00d80-6c5d-11eb-8ca5-466192785d5b.png)

Cheers!
gio

**Comment by transdigiware** [comment]
@giobb You're good at working in yours own home, I don't have one so I use a rental machine in public rental internet (Warnet[warnet ](https://id.wikipedia.org/wiki/Warung_Internet) ) to be able to reach this complicated thing.

**Comment by cgranade** [comment]
Thanks for filing this, @giobb! I've gone on and transferred it to the repo used for the `az quantum` CLI commands, and will close this issue as a result. Thanks for the report!
