### ISSUE TITLE
open Microsoft.Quantum.Arithmetic not showing Dividel operation for use.

### ISSUE THREAD

**Issue by GabrieleToffanin** [microsoft/Quantum#502]
Either for visual studio and visual studio code , when i am trying to get access to `Microsoft.Quantum.Arithmetic` operations the **operation DivideI** doesn't show up and there is no way to actually using it. Actually using Q# on Windows 10.

**Comment by cgranade** [comment]
Thanks for the bug report! The `DivideI` operation is provided by the `Microsoft.Quantum.Numerics` package, as noted in the API documentation page at https://docs.microsoft.com/qsharp/api/qsharp/microsoft.quantum.arithmetic.dividei:

![image](https://user-images.githubusercontent.com/31516/119881664-63222300-bee2-11eb-8a01-6679080d7732.png)

Did you make sure to add a package reference to `Microsoft.Quantum.Numerics`? You can see more details about how to do so at https://docs.microsoft.com/quantum/user-guide/libraries/additional-libraries. Thanks!

**Comment by GabrieleToffanin** [comment]
I have already done that by managing NuGet package's in my project . The problem have been resolved thanks to a recent update. Thank you for disponibility.
