### ISSUE TITLE
Shor notebook seems wrong/incomplete

### ISSUE THREAD

**Issue by anpaz** [microsoft/Quantum#505]
**Describe the bug**
The [Shor notebook on the integer-factorization sample](https://github.com/microsoft/Quantum/blob/main/samples/algorithms/integer-factorization/Shor.ipynb) seems wrong. The notebook doesn't compile and looks more like a notebook about scrap development notes than something that provides value to users.

**Comment by anpaz** [comment]
Let me know if we just want to delete it and I can take care of that.

**Comment by cgranade** [comment]
Ah, that's odd, I don't know how that one happened. I agree, we should go on and just delete this for now until we have a chance to prepare a nicer notebook for Shor.
