### ISSUE TITLE
Rotation should fail when the angle is NaN

### ISSUE THREAD

**Issue by liukui17** [Microsoft/Quantum#51]
Dear Microsoft Q# Developers and Researchers,

I just attended a workshop today at the University of Washington and got a chance to work through the Superposition Tutorial in Quantum-Katas. I was working on Task 9 and 10, and attempted to run some recursive code that is nonsensical in retrospect but somehow managed to pass the test cases:

```
Ry(ArcCos(1.0 / Sqrt(ToDouble(idx))) * 2.0, qs[idx]);
```

The most nonsensical part is that there is an off-by-one error in `Ry(ArcCos(1.0 / Sqrt(ToDouble(idx))) * 2.0, qs[idx]);`, when `idx=0`. ArcCos(1.0/Sqrt(ToDouble(idx))) should and does produce NaN after printing it out via "Message". But I don't understand why it passes the test cases. I'm confident this code shouldn't work so it might be the case that the Tutorial tests contain a bug (?) That or my current environment, the way I have it set up, is bugged.

Thank you very much for your time and consideration. Thanks also for developing this software and setting up the workshop here; it was loads of fun and I learned a lot. The instructors were wonderful (my apologies, I don't remember their names). Looking forward to future developments!

Best,
Kuikui

**Comment by cgranade** [comment]
Thanks for the report! We'll look into this and figure out why `Ry(ArcCos(1.0 / 0.0))` works, when I agree it really shouldn't. In the meantime, I've removed some of the code from your report so as to not spoil the fun for others going through the same tutorials; sorry for the hassle!

**Comment by anpaz-msft** [comment]
Renaming the issue to reflect the actual problem.

**Comment by anpaz-msft** [comment]
Ah, yes. It was fixed in version `0.2.1806.1503`. Thanks @RolfHuisman for pointing this out.
