### ISSUE TITLE
Q# installation issue through dotnet , VS code.

### ISSUE THREAD

**Issue by Gaurang-Belekar** [microsoft/Quantum#511]
I tried Running Q# with dotnet in VS code. I encounter the error below. I had added the Path variable in bashrc file and installed dotnet sdks and runtimes.

Still there is no output as well when I as echo $DOTNET_ROOT.

/home/gb/.nuget/packages/microsoft.quantum.sdk/0.17.2105144881/Sdk/Sdk.targets(62,5): error MSB3073: The command "dotnet "/home/gb/.nuget/packages/microsoft.quantum.sdk/0.17.2105144881/DefaultItems/../tools/utils/Microsoft.Quantum.Sdk.BuildConfiguration.dll" -v Normal --output "obj/qsharp/config/qsc.config" --QscReferences "(/home/gb/.nuget/packages/microsoft.quantum.csharpgeneration/0.17.2105144881/build//../lib/netstandard2.1/Microsoft.Quantum.CSharpGeneration.dll, -1)"" exited with code 150. [/home/gb/Desktop/Q#/HelloWorld/HelloWorld.csproj]

The build failed. Fix the build errors and run again.

**Comment by ltalirz** [comment]
Hey @Gaurang-Belekar , would you mind pointing out what the issue is (also got error code 150)?

Looking at [this](https://stackoverflow.com/questions/60255563/how-to-resolve-error-rzc-discover-exited-with-code-150) I guess it may have to do with the .NET version but it's not clear to me what exactly the problem is.

**Comment by ltalirz** [comment]
Ok, for others encountering this: the issue is indeed the version of the .NET SDK - Q# currently needs version 3.1 while the default instructions on https://docs.microsoft.com/en-gb/dotnet/core/install/linux-ubuntu#2004- currently install .NET 6.0

**Comment by Gaurang-Belekar** [comment]
@ltalirz Thank you for the reply.

I switched my work of Q# to other OS diatro(Ubuntu currently) and it works well there.

(Dont remember now which one I was using when I faced the error.)

I had followed the same documents which you have shared and it worked.

**Comment by cgranade** [comment]
To clarify, when working with Q# for standalone command-line applications, Q# + .NET, or Q# + Python via `pip`, the .NET Core SDK 3.1 is currently required (https://docs.microsoft.com/azure/quantum/install-command-line-qdk#prerequisite). When working with Q# notebooks or Q# + Python from `conda`, no .NET SDK needs to be installed.
