### ISSUE TITLE
Add multi-line comments into the language

### ISSUE THREAD

**Issue by vtomole** [Microsoft/Quantum#52]
Right now, comments begin with forward slashes `//`. I propose that you add multi-line comments `/* */` as they don't clutter a code base with multiple `//` on different lines for one comment. For documentation comments, how about adopting the doc-string implementation of Python? For example,

```
operation ApplyTwice<'T>(op : ('T => ()), target : 'T) : () {
/*
# Summary
Given an operation and a target for that operation,
applies the given operation twice.

# Input
## op
The operation to be applied.
## target
The target to which the operation is to be applied.

# Type Parameters
## 'T
The type expected by the given operation as its input.

 # Example
 ``Q#
 // Should be equivalent to the identity.
 ApplyTwice(H, qubit);
 ``

 # See Also
- Microsoft.Quantum.Primitive.H 
*/
    body {
        op(target);
        op(target);
    }
}
```

Looking forward to your feedback on this proposal.

**Comment by anpaz-msft** [comment]
This is under consideration. 
Meanwhile, may I suggest multi-cursor editing on vs-code or VS. This allows you to quickly comment multiple rows. It's a trick not many people know (I didn't know it until recently). To enable this press
`Ctrl+Alt` in VS Code or `Ctrl+Shift` in Visual Studio.

**Comment by anpaz-msft** [comment]
This is not really a bug in Libraries, so closing it.
We request that you post enhancements to the Q# and the Quantum Development Kit on https://quantum.uservoice.com/, in particular, you probably want to up-vote this:
https://quantum.uservoice.com/forums/906208-q-language/suggestions/33973828-there-are-no-multiple-line-comments
