### ISSUE TITLE
Resource estimator for factorization of 2048-bit semi prime integers

### ISSUE THREAD

**Issue by dfirnhaber** [microsoft/Quantum#553]
I am trying to run the resource estimator for factoring large integers in a quantum environment. I am under the impression that I can edit IsCoPrimeI to IsCoPrimeL within shor.qs? Having trouble working around INT32 and INT64, please help

**Comment by msoeken** [comment]
Hi @dfirnhaber. Thanks for your question. You would need to rewrite the whole sample to use `BigInt` instead of `Int` for all variables that are involved the factoring algorithm, e.g., `number`, `modulus`, and `generator`. This might also require to use some alternative arithmetic functions.

If you are interested in rewriting the sample to use `BigInt` instead of `Int` that would be great. Feel free to reach out for further questions.

**Comment by dfirnhaber** [comment]
I have been working on this project for a couple months with Microsoft azure. They have explained that at this point going forward they won't be able to help. I could use some assistance in making this experiment work. What is your availability Mathias?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dfirnhaber** [comment]
I have managed to edit the shor.qs file which was quite a bit more complicated than explained, but with your instructions i was able to infer the other changes. I am having some final errors show up in Visual Studio 2019. Below is the edited code:
`// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Microsoft.Quantum.Samples.IntegerFactorization {
    open Microsoft.Quantum.Random;
    open Microsoft.Quantum.Intrinsic;
    open Microsoft.Quantum.Arithmetic;
    open Microsoft.Quantum.Convert;
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Math;
    open Microsoft.Quantum.Oracles;
    open Microsoft.Quantum.Characterization;
    open Microsoft.Quantum.Diagnostics;

    ///////////////////////////////////////////////////////////////////////////////////////////////
    // Introduction ///////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////////

    // This sample contains Q# code implementing Shor's quantum algorithm for
    // factoring integers. The underlying modular arithmetic is implemented
    // in phase encoding, based on a paper by Stephane Beauregard who gave a
    // quantum circuit for factoring n-bit numbers that needs 2n+3 qubits and
    // O(n³log(n)) elementary quantum gates.

    /// # Summary
    /// Uses Shor's algorithm to factor the parameter `number`
    ///
    /// # Input
    /// ## number
    /// A semiprime integer to be factored
    /// ## useRobustPhaseEstimation
    /// If set to true, we use Microsoft.Quantum.Characterization.RobustPhaseEstimation and
    /// Microsoft.Quantum.Characterization.QuantumPhaseEstimation otherwise
    ///
    /// # Output
    /// Pair of numbers p > 1 and q > 1 such that p⋅q = `number`
    operation FactorSemiprimeInteger(number : BigInt, useRobustPhaseEstimation : Bool) 
    : (BigInt, BigInt) {
        // First check the most trivial case, if the provided number is even
        if (number % 2 == 0) {
            Message("An even number has been given; 2 is a factor.");
            return (number / 2, 2);
        }
        // These mutables will keep track of if we found the factors,
        // and if so, what they are. The default value for the factors
        // is (1,1).
        mutable foundFactors = false;
        mutable factors = (1, 1);

        repeat {
            // Next try to guess a number co-prime to `number`
            // Get a random integer in the interval [1,number-1]
            let generator = DrawRandomInt(1, number - 1);

            // Check if the random integer indeed co-prime using
            // Microsoft.Quantum.Math.IsCoprimeL.
            // If true use Quantum algorithm for Period finding.
            if (IsCoprimeL(generator, number)) {

                // Print a message using Microsoft.Quantum.Intrinsic.Message
                // indicating that we are doing something quantum.
                Message($"Estimating period of {generator}");

                // Call Quantum Period finding algorithm for
                // `generator` mod `number`.
                // Here we have a choice which Phase Estimation algorithm to use.
                let period = EstimatePeriod(generator, number, useRobustPhaseEstimation);

                // Set the flag and factors values if the continued fractions
                // classical algorithm succeeds.
                set (foundFactors, factors) = MaybeFactorsFromPeriod(number, generator, period);
            }
            // In this case, we guessed a divisor by accident.
            else {
                // Find a divisor using Microsoft.Quantum.Math.GreatestCommonDivisorL
                let gcd = GreatestCommonDivisorL(number, generator);
                
                // Don't forget to tell the user that we were lucky and didn't do anything
                // quantum by using Microsoft.Quantum.Intrinsic.Message.
                Message($"We have guessed a divisor of {number} to be {gcd} by accident.");

                // Set the flag `foundFactors` to true, indicating that we succeeded in finding
                // factors.
                set foundFactors = true;
                set factors = (gcd, number / gcd);
            }
        } 
        until foundFactors
        fixup {
            Message("The estimated period did not yield a valid factor, trying again.");
        }
        
        // Return the factorization
        return factors;
    }

    /// # Summary
    /// Interprets `target` as encoding unsigned little-endian integer k
    /// and performs transformation |k⟩ ↦ |gᵖ⋅k mod N ⟩ where
    /// p is `power`, g is `generator` and N is `modulus`.
    ///
    /// # Input
    /// ## generator
    /// The unsigned integer multiplicative order ( period )
    /// of which is being estimated. Must be co-prime to `modulus`.
    /// ## modulus
    /// The modulus which defines the residue ring Z mod `modulus`
    /// in which the multiplicative order of `generator` is being estimated.
    /// ## power
    /// Power of `generator` by which `target` is multiplied.
    /// ## target
    /// Register interpreted as LittleEndian which is multiplied by
    /// given power of the generator. The multiplication is performed modulo
    /// `modulus`.
    operation ApplyOrderFindingOracle(
        generator : BigInt, modulus : BigInt, power : BigInt, target : Qubit[]
    )
    : Unit
    is Adj + Ctl {
        // Check that the parameters satisfy the requirements.
        Fact(IsCoprimeL(generator, modulus), "`generator` and `modulus` must be co-prime");

        // The oracle we use for order finding essentially wraps
        // Microsoft.Quantum.Arithmetic.MultiplyByModularInteger operation
        // that implements |x⟩ ↦ |x⋅a mod N ⟩.
        // We also use Microsoft.Quantum.Math.ExpModL to compute a by which
        // x must be multiplied.
        // Also note that we interpret target as unsigned integer
        // in little-endian encoding by using Microsoft.Quantum.Arithmetic.LittleEndian
        // type.
        MultiplyByModularInteger(ExpModL(generator, power, modulus), modulus, LittleEndian(target));
    }

    /// # Summary
    /// Finds a multiplicative order of the generator
    /// in the residue ring Z mod `modulus`.
    ///
    /// # Input
    /// ## generator
    /// The unsigned integer multiplicative order ( period )
    /// of which is being estimated. Must be co-prime to `modulus`.
    /// ## modulus
    /// The modulus which defines the residue ring Z mod `modulus`
    /// in which the multiplicative order of `generator` is being estimated.
    /// ## useRobustPhaseEstimation
    /// If set to true, we use Microsoft.Quantum.Characterization.RobustPhaseEstimation and
    /// Microsoft.Quantum.Characterization.QuantumPhaseEstimation
    ///
    /// # Output
    /// The period ( multiplicative order ) of the generator mod `modulus`
    operation EstimatePeriod(
        generator : BigInt, modulus : BigInt, useRobustPhaseEstimation : Bool
    ) 
    : BigInt {
        // Here we check that the inputs to the EstimatePeriod operation are valid.
        Fact(IsCoprimeL(generator, modulus), "`generator` and `modulus` must be co-prime");

        // The variable that stores the divisor of the generator period found so far.
        mutable result = 1;

        // Number of bits in the modulus with respect to which we are estimating the period.
        let bitsize = BitSizeL(modulus);

        // The EstimatePeriod operation estimates the period r by finding an
        // approximation k/2^(bits precision) to a fraction s/r, where s is some integer.
        // Note that if s and r have common divisors we will end up recovering a divisor of r
        // and not r itself. However, if we recover enough divisors of r
        // we recover r itself pretty soon.

        // Number of bits of precision with which we need to estimate s/r to recover period r.
        // using continued fractions algorithm.
        let bitsPrecision = 2 * bitsize + 1;

        // A variable that stores our current estimate for the frequency
        // of the form s/r. 
        mutable frequencyEstimate = 0;

        repeat {

            set frequencyEstimate = EstimateFrequency(
                generator, modulus, useRobustPhaseEstimation, bitsize 
            );

            if (frequencyEstimate != 0) {
                set result = PeriodFromFrequency(modulus,frequencyEstimate, bitsPrecision, result);
            }
            else {
                Message("The estimated frequency was 0, trying again.");
            }
        }
        until(ExpModL(generator, result, modulus) == 1)
        fixup {
            Message("The estimated period from continued fractions failed, trying again.");
        }

        return result;
    }

    /// # Summary
    /// Estimates the frequency of a generator
    /// in the residue ring Z mod `modulus`.
    ///
    /// # Input
    /// ## generator
    /// The unsigned integer multiplicative order ( period )
    /// of which is being estimated. Must be co-prime to `modulus`.
    /// ## modulus
    /// The modulus which defines the residue ring Z mod `modulus`
    /// in which the multiplicative order of `generator` is being estimated.
    /// ## useRobustPhaseEstimation
    /// If set to true, we use Microsoft.Quantum.Characterization.RobustPhaseEstimation else
    /// this operation uses Microsoft.Quantum.Characterization.QuantumPhaseEstimation
    /// ## bitsize
    /// Number of bits needed to represent the modulus.
    ///
    /// # Output
    /// The numerator k of dyadic fraction k/2^bitsPrecision
    /// approximating s/r.
    operation EstimateFrequency(
        generator : BigInt, 
        modulus : BigInt,
        useRobustPhaseEstimation : Bool, 
        bitsize : BigInt
    )
    : BigInt {
        mutable frequencyEstimate = 0;
        let bitsPrecision =  2 * bitsize + 1;
        
        // Allocate qubits for the superposition of eigenstates of
        // the oracle that is used in period finding.
        use eigenstateRegister = Qubit[bitsize];

        // Initialize eigenstateRegister to 1, which is a superposition of
        // the eigenstates we are estimating the phases of.
        // We first interpret the register as encoding an unsigned integer
        // in little endian encoding.
        let eigenstateRegisterLE = LittleEndian(eigenstateRegister);
        ApplyXorInPlace(1, eigenstateRegisterLE);

        // An oracle of type Microsoft.Quantum.Oracles.DiscreteOracle
        // that we are going to use with phase estimation methods below.
        let oracle = DiscreteOracle(ApplyOrderFindingOracle(generator, modulus, _, _));

        if (useRobustPhaseEstimation) {

            // Use Microsoft.Quantum.Characterization.RobustPhaseEstimation to estimate s/r.
            // RobustPhaseEstimation needs only one extra qubit, but requires
            // several calls to the oracle.
            let phase = RobustPhaseEstimation(bitsPrecision, oracle, eigenstateRegisterLE!);
            
            // Compute the numerator k of dyadic fraction k/2^bitsPrecision
            // approximating s/r. Note that phase estimation projects on the eigenstate
            // corresponding to random s.
            set frequencyEstimate = Round(((phase * BigIntAsDouble(2 ^ bitsPrecision)) / 2.0) / PI());
        }
        else {
            // Use Microsoft.Quantum.Characterization.QuantumPhaseEstimation to estimate s/r.
            // When using QuantumPhaseEstimation we will need extra `bitsPrecision`
            // qubits
            use register = Qubit[bitsPrecision];
            let frequencyEstimateNumerator = LittleEndian(register);  

            // The register that will contain the numerator k of
            // dyadic fraction k/2^bitsPrecision. The numerator is an unsigned
            // integer encoded in big-endian format. This is indicated by
            // use of Microsoft.Quantum.Arithmetic.BigEndian type.
            QuantumPhaseEstimation(
                oracle, eigenstateRegisterLE!, LittleEndianAsBigEndian(frequencyEstimateNumerator)
            ); 
            
            // Directly measure the numerator k of dyadic fraction k/2^bitsPrecision
            // approximating s/r. Note that phase estimation project on
            // the eigenstate corresponding to random s.
            set frequencyEstimate = MeasureInteger(frequencyEstimateNumerator);
        }
        
        // Return all the qubits used for oracle's eigenstate back to 0 state
        // using Microsoft.Quantum.Intrinsic.ResetAll.
        ResetAll(eigenstateRegister);

        return frequencyEstimate;
    }

    /// # Summary
    /// Find the period of a number from an input frequency.
    ///
    /// # Input
    /// ## modulus
    /// The modulus which defines the residue ring Z mod `modulus`
    /// in which the multiplicative order of `generator` is being estimated.
    /// ## frequencyEstimate
    /// The frequency that we want to convert to a period. 
    /// ## bitsPrecision
    /// Number of bits of precision with which we need to 
    /// estimate s/r to recover period r using continued 
    /// fractions algorithm.
    /// ## currentDivisor
    /// The divisor of the generator period found so far.
    ///
    /// # Output
    /// The period as calculated from the estimated frequency via
    /// the continued fractions algorithm.
    ///
    /// # See Also
    /// - Microsoft.Quantum.Math.ContinuedFractionConvergentL
    function PeriodFromFrequency(
        modulus : BigInt, 
        frequencyEstimate : BigInt, 
        bitsPrecision : BigInt, 
        currentDivisor : BigInt
    )
    : BigInt {
        
        // Now we use Microsoft.Quantum.Math.ContinuedFractionConvergentL
        // function to recover s/r from dyadic fraction k/2^bitsPrecision.
        let (numerator, period) = (ContinuedFractionConvergentL(Fraction(frequencyEstimate, 2 ^ bitsPrecision), modulus))!;
        
        // ContinuedFractionConvergentL does not guarantee the signs of the numerator
        // and denominator. Here we make sure that both are positive using
        // AbsL.
        let (numeratorAbs, periodAbs) = (AbsL(numerator), AbsL(period));

        // Return the newly found divisor.
        // Uses Microsoft.Quantum.Math.GreatestCommonDivisorL function from Microsoft.Quantum.Math.
        return (periodAbs * currentDivisor) / GreatestCommonDivisorL(currentDivisor, periodAbs);
    }

    /// # Summary
    /// Tries to find the factors of `modulus` given a `period` and `generator`.
    ///
    /// # Input
    /// ## modulus
    /// The modulus which defines the residue ring Z mod `modulus`
    /// in which the multiplicative order of `generator` is being estimated.
    /// ## generator
    /// The unsigned integer multiplicative order ( period )
    /// of which is being estimated. Must be co-prime to `modulus`.
    /// ## period
    /// The estimated period ( multiplicative order ) of the generator mod `modulus`.
    ///
    /// # Output
    /// A tuple of a flag indicating whether factors were found successfully,
    /// and a pair of integers representing the factors that were found.
    /// Note that the second output is only meaningful when the first
    /// output is `true`.
    ///
    /// # See Also
    /// - Microsoft.Quantum.Math.GreatestCommonDivisorL
    function MaybeFactorsFromPeriod(modulus : BigInt, generator : BigInt, period : BigInt) 
    : (Bool, (BigInt, BigInt)) {
        // Period finding reduces to factoring only if period is even
        if (period % 2 == 0) {
            
            // Compute `generator` ^ `period/2` mod `number`
            // using Microsoft.Quantum.Math.ExpModL.
            let halfPower = ExpModL(generator, period / 2, modulus);

            // If we are unlucky, halfPower is just -1 mod N,
            // which is a trivial case and not useful for factoring.
            if (halfPower != modulus - 1) {

                // When the halfPower is not -1 mod N
                // halfPower-1 or halfPower+1 share non-trivial divisor with `number`.
                // We find a divisor Microsoft.Quantum.Math.GreatestCommonDivisorL.
                let factor = MaxI(
                    GreatestCommonDivisorL(halfPower - 1, modulus), 
                    GreatestCommonDivisorL(halfPower + 1, modulus)
                );
                
                // Add a flag that we found the factors, and return computed non-trivial factors.
                return (true, (factor, modulus / factor));
            } else {
                // Return a flag indicating we hit a trivial case and didn't get any factors.
                return (false, (1,1));
            }
        } else {
            // When period is odd we have to pick another generator to estimate
            // period of and start over.
            Message("Estimated period was odd, trying again.");
            return (false, (1,1));
        }
    }
}
`
There are some final errors that i am not sure how to edit within program.cs and FlameGraphResourcesEstimator.cs.
The specific errors are CS0103: The names FactorSemiPrimeInteger and EstimateFrequency do not exist in the current context. Finally, within the FlameGraphResourcesEstimator is a warning CS8602: Dereference of a possibly null reference. 

I had to leave some Int's like within 'generator = DrawRandomInt' but had to change some to BigInt's as in 'set frequencyEstimate = Round(((phase * BigIntAsDouble...'
I changed I's to L's within 'gcd = GreatestCommonDivisorL, ExpModL, and bitsize = BitSizeL.' 

I believe it is close to working. How should I deal with the Program.cs errors and why it is giving a warning from the FlameGraph file? Is there anything else i am missing?

**Comment by msoeken** [comment]
Is the whole project code somewhere online (or through Github) to have a complete look into the problems?

For `FactorSemiPrimeInteger`, this may be a typo, as it is called `FactorSemiprimeInteger` in the code above? And I wonder whether you are running into a name clash with `EstimateFrequency` because another operation is defined in `Microsoft.Quantum.Characterization` (see [here](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.characterization.estimatefrequency))

**Comment by dfirnhaber** [comment]
I looked back over the code and the FactorSemiprimeInteger is written correctly. From what I am gathering the issues are coming up from the read-only struct int32 and int64 within the program file. I would like to give you access to this project. Is there an easy way? The sub-directories within Microsoft quantum development kit include algorithms/factorization. Within factorization, there are the following files: shor.qs, program.cs, and the flamegraph files. Within program.cs I am editing the default number to be factored to my 617-digit semi-prime integer. This is where the original problem lies. The number is too big. To fix this error I have attempted rewriting shor.qs to handle bigInt. Is there an easier way to complete this simulation?

**Comment by msoeken** [comment]
@dfirnhaber There hasn't been an update in a while and therefore I am closing this issue. Please feel free to re-open it, if there are further questions. Thanks again for opening this issue and your helpful comments in this thread.

**Comment by dfirnhaber** [comment]
I apologize for not responding sooner. I have been working on another stage of this project and have not been able to apply your newest instructions yet.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by msoeken** [comment]
No problem at all. Feel free to re-open this issue, if there are further questions
