### ISSUE TITLE
 using azure for 40 qubit

### ISSUE THREAD

**Issue by EnginSahinCE** [Microsoft/Quantum#57]
How to simulate using azure for 40 qubit with microsoft quantum dev.kit (MQDK)? What do we need to do for azure and MQDK?

**Comment by jhenshaw** [comment]
Hi @EnginSahinCE - thanks for the question. As of now, our higher-scale simulator is available only to customer with whom we are doing collaborative development. We are exploring making it available to broader audiences at a later time. If your simulation scenario requires 40 qubits and you'd like to explore early access [it may be paid access], feel free to shoot me an email at JHenshaw@microsoft.com.
