### ISSUE TITLE
Q# to C# compiler generates wrong decimal point on non-english computers

### ISSUE THREAD

**Issue by StLange** [Microsoft/Quantum#6]
Compilation fails on my German computer, because the generated C# code contains ',' instead of '.' as decimal separator. Switching Windows to English number format fixes the issue.
That means there is at least one double to string conversion in the Q# compiler that misses CultureInfo.InvariantCulture and uses regional number format (German uses comma as decimal point).

**Comment by helpsterTee** [comment]
Confirming this issue. Even the Microsoft.Quantum.Canon library is not compilable from the "Installing and Validating the Q# Development Environment" tutorial in the documentation.

Errors thrown:
![Compilation errors](https://i.imgur.com/HWYawmN.png)

Fixable by @StLange 's supposed workaround.

**Comment by quixoticaxis** [comment]
Confirming the  issue, haven't tried the workaround yet.
Everything is filled with comma-delimited values on Windows 10 with Russian locale.

**Comment by alan-geller** [comment]
I can confirm that this is indeed a bug. Thanks for reporting it!!
I've created a bug in our tracking database and we'll evaluate it for a future update. In the meantime, setting Windows to use US number format should fix the issue.

**Comment by alan-geller** [comment]
Closing here; will track this at https://quantum.uservoice.com/forums/906097-general-ideas-and-feature-requests/suggestions/32603518-q-compiler-fails-with-decimal-separator-other-tha.
