### ISSUE TITLE
Can't create new Q# Project

### ISSUE THREAD

**Issue by willdeuschle** [Microsoft/Quantum#74]
Running `dotnet new console -lang Q# --output Bell` for the Hello World project results in this error:

`'Q#' is not a valid value for -lang (language).`

This is with dotnet version 2.1.301.

I'm unclear if this is a Quantum problem or dotnet problem

**Comment by anpaz-msft** [comment]
Did you follow the instructions on how to install the QDK and project templates:
https://docs.microsoft.com/en-us/quantum/quantum-installconfig?view=qsharp-preview&tabs=tabid-vscode#

Looks like you are missing installing the Project Templates:
`dotnet new -i "Microsoft.Quantum.ProjectTemplates::0.2.1806.3001-preview"`

**Comment by willdeuschle** [comment]
I did in fact run that command originally. However, there's a difference between the command you provided and the one that is listed in the docs at that link:

![image](https://user-images.githubusercontent.com/16803992/42160213-603fabce-7dc4-11e8-873b-1f633cd956e0.png)

You can see that command is `dotnet new -i "Microsoft.Quantum.ProjectTemplates::0.2.1806.2802-preview"`, while the one you suggested is `dotnet new -i "Microsoft.Quantum.ProjectTemplates::0.2.1806.3001-preview"`. After running the second command, it worked! It would be great if that link could be updated to reflect this. Thanks for the help.

**Comment by anpaz-msft** [comment]
Glad to hear it is working now for you. I just picked up the latest version, but 2802 will also work.
