### ISSUE TITLE
August 11, 2018 Dependency error in Microsoft Development Kit with latest Visual Studio 2017 Community

### ISSUE THREAD

**Issue by taotaotao3** [Microsoft/Quantum#78]
Hello.
August 11, 2018 When installing the latest Visual Studio 2017 Community, deploying github of Microsoft development kit (MDK) to solution, and executing teleportation, 48 errors and dependency warning appeared in Nuget and MDK. How can we solve it?
![image](https://user-images.githubusercontent.com/20910951/43985467-935f5e9e-9d42-11e8-9653-66f7d3296600.png)

![image](https://user-images.githubusercontent.com/20910951/43985434-66796334-9d42-11e8-9403-72842b5c6f10.png)

![image](https://user-images.githubusercontent.com/20910951/43985512-d9098bb8-9d42-11e8-8f6c-67b7ed21fc7f.png)

ーーー
example)
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	MSB3073	コマンド "dotnet "C:\Users\user\.nuget\packages\microsoft.quantum.development.kit\0.2.1806.3001-preview\build\../tools/qsc/qsc.dll" --input "DatabaseSearch.qs" --references "C:\Users\user\Source\Repos\Quantum\Microsoft.Quantum.Canon\bin\Debug\netstandard2.0\Microsoft.Quantum.Canon.dll" "C:\Users\user\.nuget\packages\microsoft.quantum.development.kit\0.2.1806.3001-preview\lib\netstandard2.0\Microsoft.Quantum.MetaData.dll" "C:\Users\user\.nuget\packages\microsoft.quantum.development.kit\0.2.1806.3001-preview\lib\netstandard2.0\Microsoft.Quantum.Primitives.dll" "C:\Users\user\.nuget\packages\microsoft.quantum.development.kit\0.2.1806.3001-preview\lib\netstandard2.0\Microsoft.Quantum.Simulation.Common.dll" "C:\Users\user\.nuget\packages\microsoft.quantum.development.kit\0.2.1806.3001-preview\lib\netstandard2.0\Microsoft.Quantum.Simulation.Core.dll" "C:\Users\user\.nuget\packages\microsoft.quantum.development.kit\0.2.1806.3001-preview\lib\netstandard2.0\Microsoft.Quantum.Simulation.QCTraceSimulatorRuntime.dll" "C:\Users\user\.nuget\packages\microsoft.quantum.development.kit\0.2.1806.3001-preview\lib\netstandard2.0\Microsoft.Quantum.Simulation.Simulators.dll" --outputpath obj\qsharp\src\" はコード -10 で終了しました。	DatabaseSearchSample	C:\Users\user\.nuget\packages\microsoft.quantum.development.kit\0.2.1806.3001-preview\build\Microsoft.Quantum.Development.Kit.targets	17	
ーーー

Before debugging dependency warning mark

48 error during debugging.

![image](https://user-images.githubusercontent.com/20910951/43985650-e132b89a-9d43-11e8-8e11-e44dcc0ce99f.png)

error example)
Predefined type 'system.string' is not defined or imported

'object' does not include a constructor specifying argument 0.

Predefined type 'system.Object' is not defined or imported

CS0246 Name or namespace name 'QuantumSimulator' was not found (please make sure that the using directive or assembly reference is specified).

Predefined type 'system.lnt32' has not been defined or imported

Predefined type 'system.Boolean' has not been defined or imported

**Comment by alan-geller** [comment]
Sometimes Visual Studio reports spurious IntelliSense errors, especially before and during the first time you build a Q# project. Since the sample ran successfully, I suspect that's what happened, and most of these errors and warnings should go away if you recompile.

We're working on ways to improve this experience; it requires some substantial changes to the way we integrate into VS.
