### ISSUE TITLE
Visual Studio Quantum Development Kit  IntegerFactorization's Speed

### ISSUE THREAD

**Issue by taotaotao3** [Microsoft/Quantum#79]
Visual Studio Microsoft Quantum Development Kit has the speed of a quantum computer, is not it?

Is it 100 million times faster than a classical supercomputer?

Quantum / Samples / IntegerFactorization /
I did not feel the speed if factoring decomposition using Shore's algorithm here.
Why?

In addition, here we are using long type in C #. With this, the number of digits is insufficient when prime factorization of the product (modulus) of prime numbers generated from a 64-bit public key.

![image](https://user-images.githubusercontent.com/20910951/44000734-64fcf650-9e60-11e8-934f-f968f6ac6b54.png)

I was hoping for a quantum computer. It is possible to solve prime factorization which was an answer time to become an astronomical figure in a short time.

**Comment by alan-geller** [comment]
The Quantum Development Kit uses a classical simulator to simulate small quantum computations on a classical computer. It does not have the speed of some potential future quantum computer. Sorry!!
