### ISSUE TITLE
Integer Factorization Sample

### ISSUE THREAD

**Issue by jean002** [Microsoft/Quantum#81]
I have tried to run Shor's algorithm on Visual Studio 2017, but there was an error message, saying that "period" in the qs file was undefined. The problem was that "period" was defined as EstimatePeriod(coprimeCandidate, number, useRobustPhaseEstimation). But the "EstimatePeriod" operation was defined after the "Shor" operation, in which "period" is defined. I've moved the codes for "EstimatePeriod" before the codes for "Shor". Now, it runs fine.

If needed, I can share the edited file.

**Comment by RolfHuisman** [comment]
Might be a caching issue. Can you share your version numbers of the tooling you are using ? Can't repro this on Windows 10 with 2017 Enterprise version 15.8.3 and the Q# SDK 0.2.1806.3001

**Comment by anpaz-msft** [comment]
The order in which operations are defined in Q# is not important.
Could you be a bit more specific on when/where did you see the error? If it was on the error window of Visual Studio when you open the solution: be aware that Visual Studio's Intellisense sometimes report errors the first time you open the solution until you actually compile the project and sometimes until you actually restart Visual Studio. Building and running the samples, though, should work fine. Let us know.

**Comment by jean002** [comment]
I use the free version of Visual Studio 2017 on Windows 10.

The error message appeared on the output window, at the bottom of the page. I have recently opened a new solution and new project and pasted the algorithm unchanged. It now runs fine.

**Comment by anpaz-msft** [comment]
I'm closing this, as it seems to be working now.
