### ISSUE TITLE
Issue adding Microsoft.Quantum.Canon NuGet package to UWP project

### ISSUE THREAD

**Issue by rickengle** [Microsoft/Quantum#83]
Hi, while I could add the Microsoft.Quantum.Development.Kit NuGet package to my Windows 10 C# UWP project, when I tried to add the Microsoft.Quantum.Canon package as well I got this issue:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.Quantum.Canon 0.2.1809.701-preview is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063). Package Microsoft.Quantum.Canon 0.2.1809.701-preview supports: netstandard2.0 (.NETStandard,Version=v2.0)	

Do you have some UWP compatible packages?  I don't want to be limited to a C# Console app as the host app.

Thanks,
  Rick

**Comment by RolfHuisman** [comment]
You need to switch the minimum supported version to "build 16299", because there support for dotnetcore 2.0 was introduced to UAP. Seee https://github.com/dotnet/standard/issues/462 for more information.
