### ISSUE TITLE
AdiabaticIsing

### ISSUE THREAD

**Issue by jean002** [Microsoft/Quantum#89]
Hi,

I have run the sample AdiabaticIsing in Visual Studio 2017 free edition, and I have got these errors (see attachment):

[AdiabaticIsing.pdf](https://github.com/Microsoft/Quantum/files/2452067/AdiabaticIsing.pdf)

Does anyone have any similar errors?

**Comment by RolfHuisman** [comment]
Errors like these sometimes happens if the compile was not directly successful and the caches are corrupted. They are changing the way the integration of visual studio works, so these problems should dissapear then.

In the meantime, as a workaround; first try a rebuild. If that doesn't fix it, close visual studio, clean out the obj and bin folder, re-open in visual studio and recompile. Usually this works for me to get them compiled again.

**Comment by jean002** [comment]
When I clean out the obj and bin folders and rebuild, all the C# errors are gone but all the Q# errors remain.

**Comment by anpaz-msft** [comment]
Hi @jean002.
Looking at your screenshot, the errors are coming from a project called "Samples - Test", which is not a project that is part of this repository. I also see a "Driver.cs" listed in there, which is a file that is not part of the Adiabatic sample.
I also noticed that there are errors for an undefined `hxCoupling` on line 721 of an `Operation.qs` file.
I couldn't find any file that has that variable on line 721... 

My guess is that your tried creating a new project and that your forgot to add some references or that you copy/paste some code and something went wrong.

My recommendation is to first try to build and run the Adiabatic Ising Evalution sample as-is, all you should need is to open and build the project in Visual Studio (full instructions can be found in the [README.md](https://github.com/Microsoft/Quantum/tree/master/Samples/AdiabaticIsing), once that is working you can try editing the existing sample or create your new project.

Good luck! Do let us know if you are having problem the solution from the repository.

**Comment by jean002** [comment]
It builds perfectly, but an error message "A project with an Output Type of Class Library cannot be started directly" appears when trying to debug it.
